spring:
  application:
    name: SpringApp
server:
  port: 8001
#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus,health,metrics
#  prometheus:
#    metrics:
#      export:
#        enabled: true
